import type { NiriInstallConfig, Distro } from "./install-context"

function getInstallCommand(distro: Distro, packages: string[]): string {
  const pkgMap: Record<Distro, Record<string, string>> = {
    arch: {
      "fuzzel": "fuzzel",
      "polkit-gnome": "polkit-gnome",
      "nm-connection-editor": "nm-connection-editor",
      "xdg-desktop-portal-gnome": "xdg-desktop-portal-gnome",
      "xwayland-satellite": "xwayland-satellite",
    },
    fedora: {
      "fuzzel": "fuzzel",
      "polkit-gnome": "polkit-gnome",
      "nm-connection-editor": "nm-connection-editor",
      "xdg-desktop-portal-gnome": "xdg-desktop-portal-gnome",
      "alacritty": "alacritty",
      "thunar": "thunar",
      "swaybg": "swaybg",
    },
    ubuntu: {
      "fuzzel": "fuzzel",
      "polkit-gnome": "policykit-1-gnome",
      "nm-connection-editor": "nm-connection-editor",
      "xdg-desktop-portal-gnome": "xdg-desktop-portal-gnome",
      "swaybg": "swaybg",
    },
    void: {
      "fuzzel": "fuzzel",
      "polkit-gnome": "polkit-gnome",
      "nm-connection-editor": "NetworkManager-gnome",
      "xdg-desktop-portal-gnome": "xdg-desktop-portal-gnome",
    },
    opensuse: {
      "fuzzel": "fuzzel",
      "polkit-gnome": "polkit-gnome",
      "nm-connection-editor": "NetworkManager-connection-editor",
      "xdg-desktop-portal-gnome": "xdg-desktop-portal-gnome",
    },
  }

  const mapped = packages.map((pkg) => pkgMap[distro]?.[pkg] ?? pkg)
  const pkgList = mapped.join(" ")

  switch (distro) {
    case "arch":
      return `sudo pacman -S --needed --noconfirm ${pkgList}`
    case "fedora":
      return `sudo dnf install -y ${pkgList}`
    case "ubuntu":
      return `sudo apt install -y ${pkgList}`
    case "void":
      return `sudo xbps-install -S ${pkgList}`
    case "opensuse":
      return `sudo zypper install -y ${pkgList}`
  }
}

function generateNiriKdl(c: NiriInstallConfig): string {
  const lines: string[] = []

  lines.push("// Niri Configuration")
  lines.push("// Generated by Linux Themer")
  lines.push("")

  // Environment variables
  if (c.envVars.length > 0) {
    lines.push("environment {")
    for (const e of c.envVars) {
      lines.push(`    ${e.key} "${e.value}"`)
    }
    lines.push("}")
    lines.push("")
  }

  // Input
  lines.push("input {")
  lines.push("    keyboard {")
  lines.push("        xkb {")
  lines.push(`            layout "${c.kbLayout}"`)
  if (c.kbVariant) lines.push(`            variant "${c.kbVariant}"`)
  if (c.kbOptions) lines.push(`            options "${c.kbOptions}"`)
  lines.push("        }")
  lines.push(`        repeat-rate ${c.repeatRate}`)
  lines.push(`        repeat-delay ${c.repeatDelay}`)
  lines.push("    }")
  lines.push("")
  lines.push("    touchpad {")
  if (c.touchpadTapToClick) lines.push("        tap")
  if (c.touchpadNaturalScroll) lines.push("        natural-scroll")
  if (c.touchpadDisableWhileTyping) lines.push("        dwt")
  lines.push(`        accel-profile "${c.mouseAccelProfile}"`)
  lines.push("    }")
  lines.push("")
  lines.push("    mouse {")
  if (c.naturalScroll) lines.push("        natural-scroll")
  lines.push(`        accel-profile "${c.mouseAccelProfile}"`)
  lines.push("    }")
  lines.push("}")
  lines.push("")

  // Layout
  lines.push("layout {")
  lines.push(`    gaps ${c.gapsIn}`)
  lines.push(`    center-focused-column "${c.centerFocusedColumn}"`)
  lines.push("")
  lines.push("    preset-column-widths {")
  lines.push("        proportion 0.33333")
  lines.push("        proportion 0.5")
  lines.push("        proportion 0.66667")
  lines.push("    }")
  lines.push("")
  lines.push(`    default-column-width { ${c.defaultColumnWidth}; }`)
  lines.push("")
  lines.push("    focus-ring {")
  lines.push(`        width ${c.focusRingWidth}`)
  lines.push(`        active-color "${c.focusRingColor}"`)
  lines.push(`        inactive-color "${c.inactiveColor}"`)
  lines.push("    }")
  lines.push("")
  lines.push("    border {")
  lines.push("        off")
  lines.push("    }")
  lines.push("")
  lines.push("    struts {")
  lines.push(`        left ${c.gapsOut}`)
  lines.push(`        right ${c.gapsOut}`)
  lines.push(`        top ${c.gapsOut}`)
  lines.push(`        bottom ${c.gapsOut}`)
  lines.push("    }")
  lines.push("}")
  lines.push("")

  lines.push("prefer-no-csd")
  lines.push("")

  // Animations
  const easing = c.animationStyle === "spring"
    ? "spring damping-ratio=0.6 stiffness=800 epsilon=0.0001"
    : c.animationStyle === "ease-out-expo"
    ? 'easing-curve "ease-out-expo"'
    : 'easing-curve "ease-out-cubic"'

  lines.push("animations {")
  if (!c.animationEnabled) {
    lines.push("    off")
  } else {
    lines.push(`    slowdown ${c.animationSpeed}`)
    lines.push("")
    const anims = ["workspace-switch", "window-open", "window-close", "horizontal-view-movement", "window-movement", "window-resize"]
    const durations = [250, 200, 150, 250, 200, 200]
    for (let i = 0; i < anims.length; i++) {
      lines.push(`    ${anims[i]} {`)
      lines.push(`        ${easing}`)
      lines.push(`        duration-ms ${Math.round(durations[i] / c.animationSpeed)}`)
      lines.push("    }")
      if (i < anims.length - 1) lines.push("")
    }
  }
  lines.push("}")
  lines.push("")

  // Window Rules
  lines.push("window-rule {")
  lines.push(`    geometry-corner-radius ${c.borderRadius}`)
  lines.push("    clip-to-geometry true")
  lines.push("}")
  lines.push("")

  if (c.windowRules.length > 0) {
    for (const rule of c.windowRules) {
      lines.push("window-rule {")
      lines.push(`    match ${rule.match}`)
      for (const r of rule.rules) {
        lines.push(`    ${r}`)
      }
      lines.push("}")
      lines.push("")
    }
  }

  // Spawn at startup
  if (c.spawnAtStartup.length > 0) {
    for (const cmd of c.spawnAtStartup) {
      const parts = cmd.split(" ")
      if (parts.length > 1) {
        lines.push(`spawn-at-startup "${parts[0]}" ${parts.slice(1).map(a => `"${a}"`).join(" ")}`)
      } else {
        lines.push(`spawn-at-startup "${cmd}"`)
      }
    }
    lines.push("")
  }

  // Keybinds
  lines.push("binds {")
  for (const bind of c.keybinds) {
    const mods = bind.mods.join("+")
    const key = bind.key
    const args = bind.args ? ` "${bind.args}"` : ""
    lines.push(`    ${mods}+${key} { ${bind.action}${args}; }`)
  }
  lines.push("}")

  return lines.join("\n")
}

function generateWaybarConfig(c: NiriInstallConfig): string {
  return JSON.stringify(
    {
      layer: "top",
      position: c.barPosition,
      height: c.barHeight,
      spacing: c.barModuleSpacing,
      "modules-left": ["niri/workspaces"],
      "modules-center": ["clock"],
      "modules-right": [
        "pulseaudio",
        "network",
        ...(c.packages.includes("brightnessctl") ? ["backlight"] : []),
        "battery",
        "tray",
      ],
      "niri/workspaces": {
        format: "{icon}",
        "format-icons": {
          active: "",
          default: "",
        },
      },
      clock: {
        format: "{:%H:%M}",
        "format-alt": "{:%A, %B %d, %Y}",
        "tooltip-format": "<tt>{calendar}</tt>",
      },
      battery: {
        states: { warning: 30, critical: 15 },
        format: "{icon} {capacity}%",
        "format-icons": ["", "", "", "", ""],
      },
      network: {
        "format-wifi": " {signalStrength}%",
        "format-ethernet": " {ipaddr}",
        "format-disconnected": "⚠ Disconnected",
      },
      pulseaudio: {
        format: "{icon} {volume}%",
        "format-muted": " Muted",
        "format-icons": { default: ["", "", ""] },
        "on-click": "pavucontrol",
      },
    },
    null,
    2
  )
}

function generateWaybarCSS(c: NiriInstallConfig): string {
  return `/* Waybar CSS — Generated by Linux Themer */

* {
    font-family: "JetBrains Mono", "Font Awesome 6 Free", monospace;
    font-size: ${c.barFontSize + 2}px;
}

window#waybar {
    background-color: ${c.barBg};
    color: ${c.barText};
    opacity: ${c.barOpacity};${c.barBorderRadius > 0 ? `\n    border-radius: ${c.barBorderRadius}px;` : ""}${c.barMargin > 0 ? `\n    margin: ${c.barMargin}px;` : ""}
}

#workspaces button {
    padding: 2px 8px;
    color: ${c.barText};
    background: transparent;
    border-radius: ${c.barModuleRadius}px;
    margin: 0 ${c.barModuleSpacing}px;
    border: none;
}

#workspaces button.active {
    background: ${c.accentColor};
    color: ${c.barBg};
}

#workspaces button:hover {
    background: rgba(255, 255, 255, 0.1);
}

#clock,
#network,
#pulseaudio,
#battery,
#backlight,
#tray {
    padding: 2px 10px;
    margin: 4px ${c.barModuleSpacing}px;
    background: ${c.barModuleBg};
    border-radius: ${c.barModuleRadius}px;
    color: ${c.barText};
}

#clock {
    color: ${c.accentColor};
    font-weight: bold;
}

#battery.warning {
    color: #f9e2af;
}

#battery.critical {
    color: #f38ba8;
}`
}

export function generateInstallScript(config: NiriInstallConfig): string {
  const lines: string[] = []

  lines.push("#!/bin/bash")
  lines.push("")
  lines.push("# ╔══════════════════════════════════════════════════════════════╗")
  lines.push("# ║  Niri Installer — Generated by Linux Themer                 ║")
  lines.push("# ║  https://linux-themer.dev                                   ║")
  lines.push("# ╚══════════════════════════════════════════════════════════════╝")
  lines.push("")
  lines.push('set -e')
  lines.push("")

  lines.push("# Colors")
  lines.push('GREEN="\\033[0;32m"')
  lines.push('BLUE="\\033[0;34m"')
  lines.push('YELLOW="\\033[0;33m"')
  lines.push('NC="\\033[0m"')
  lines.push("")

  lines.push('echo -e "${BLUE}╔══════════════════════════════════════════╗${NC}"')
  lines.push('echo -e "${BLUE}║     Niri Installer                       ║${NC}"')
  lines.push('echo -e "${BLUE}╚══════════════════════════════════════════╝${NC}"')
  lines.push('echo ""')
  lines.push("")

  // Install packages
  lines.push("# ── Install Packages ──────────────────────────────────────────")
  lines.push('echo -e "${YELLOW}Installing packages...${NC}"')
  lines.push(getInstallCommand(config.distro, config.packages))
  lines.push('echo -e "${GREEN}✓ Packages installed${NC}"')
  lines.push('echo ""')
  lines.push("")

  // Create directories
  lines.push("# ── Create Config Directories ─────────────────────────────────")
  lines.push("mkdir -p ~/.config/niri")
  lines.push("mkdir -p ~/.config/waybar")
  lines.push("mkdir -p ~/.config/dunst")
  lines.push('echo -e "${GREEN}✓ Config directories created${NC}"')
  lines.push("")

  // Write niri config
  const niriConf = generateNiriKdl(config)
  lines.push("# ── Write Niri Config ─────────────────────────────────────────")
  lines.push('echo -e "${YELLOW}Writing config.kdl...${NC}"')
  lines.push("cat > ~/.config/niri/config.kdl << 'NIRICONF'")
  lines.push(niriConf)
  lines.push("NIRICONF")
  lines.push('echo -e "${GREEN}✓ config.kdl written${NC}"')
  lines.push("")

  // Write waybar config
  const waybarConfig = generateWaybarConfig(config)
  lines.push("# ── Write Waybar Config ───────────────────────────────────────")
  lines.push('echo -e "${YELLOW}Writing waybar config...${NC}"')
  lines.push("cat > ~/.config/waybar/config.jsonc << 'WAYBARCONF'")
  lines.push(waybarConfig)
  lines.push("WAYBARCONF")
  lines.push('echo -e "${GREEN}✓ Waybar config written${NC}"')
  lines.push("")

  // Write waybar CSS
  const waybarCSS = generateWaybarCSS(config)
  lines.push("# ── Write Waybar CSS ──────────────────────────────────────────")
  lines.push('echo -e "${YELLOW}Writing waybar style.css...${NC}"')
  lines.push("cat > ~/.config/waybar/style.css << 'WAYBARCSS'")
  lines.push(waybarCSS)
  lines.push("WAYBARCSS")
  lines.push('echo -e "${GREEN}✓ Waybar CSS written${NC}"')
  lines.push("")

  // Write dunst config
  if (config.packages.includes("dunst")) {
    lines.push("# ── Write Dunst Config ───────────────────────────────────────")
    lines.push('echo -e "${YELLOW}Writing dunst config...${NC}"')
    lines.push("cat > ~/.config/dunst/dunstrc << 'DUNSTCONF'")
    lines.push("[global]")
    lines.push(`    frame_color = "${config.accentColor}"`)
    lines.push("    font = JetBrains Mono 10")
    lines.push(`    frame_width = ${config.focusRingWidth}`)
    lines.push(`    corner_radius = ${config.borderRadius}`)
    lines.push("")
    lines.push("[urgency_low]")
    lines.push(`    background = "${config.windowBg}"`)
    lines.push(`    foreground = "${config.barText}"`)
    lines.push("")
    lines.push("[urgency_normal]")
    lines.push(`    background = "${config.windowBg}"`)
    lines.push(`    foreground = "${config.barText}"`)
    lines.push("")
    lines.push("[urgency_critical]")
    lines.push(`    background = "${config.windowBg}"`)
    lines.push('    foreground = "#f38ba8"')
    lines.push(`    frame_color = "#f38ba8"`)
    lines.push("DUNSTCONF")
    lines.push('echo -e "${GREEN}✓ Dunst config written${NC}"')
    lines.push("")
  }

  // Done
  lines.push("# ── Done ─────────────────────────────────────────────────────")
  lines.push('echo ""')
  lines.push('echo -e "${GREEN}╔══════════════════════════════════════════╗${NC}"')
  lines.push('echo -e "${GREEN}║     Installation Complete!               ║${NC}"')
  lines.push('echo -e "${GREEN}╚══════════════════════════════════════════╝${NC}"')
  lines.push('echo ""')
  lines.push('echo -e "Your Niri setup is ready."')
  lines.push('echo -e "Log out and select ${BLUE}niri${NC} from your display manager."')
  lines.push('echo -e "Or run: ${BLUE}niri-session${NC} from a TTY."')

  return lines.join("\n")
}
