import type { HyprInstallConfig, Distro } from "./install-context"

function getInstallCommand(distro: Distro, packages: string[]): string {
  const pkgMap: Record<Distro, Record<string, string>> = {
    arch: {
      "rofi-wayland": "rofi-wayland",
      "polkit-gnome": "polkit-gnome",
      "nm-connection-editor": "nm-connection-editor",
      "xdg-desktop-portal-hyprland": "xdg-desktop-portal-hyprland",
    },
    fedora: {
      "rofi-wayland": "rofi-wayland",
      "polkit-gnome": "polkit-gnome",
      "nm-connection-editor": "nm-connection-editor",
      "xdg-desktop-portal-hyprland": "xdg-desktop-portal-hyprland",
      "kitty": "kitty",
      "thunar": "thunar",
      "hyprpaper": "hyprpaper",
    },
    ubuntu: {
      "rofi-wayland": "rofi",
      "polkit-gnome": "policykit-1-gnome",
      "nm-connection-editor": "nm-connection-editor",
      "xdg-desktop-portal-hyprland": "xdg-desktop-portal-hyprland",
      "hyprpaper": "hyprpaper",
    },
    void: {
      "rofi-wayland": "rofi-wayland",
      "polkit-gnome": "polkit-gnome",
      "nm-connection-editor": "NetworkManager-gnome",
      "xdg-desktop-portal-hyprland": "xdg-desktop-portal-hyprland",
    },
    opensuse: {
      "rofi-wayland": "rofi-wayland",
      "polkit-gnome": "polkit-gnome",
      "nm-connection-editor": "NetworkManager-connection-editor",
      "xdg-desktop-portal-hyprland": "xdg-desktop-portal-hyprland",
    },
  }

  const mapped = packages.map((pkg) => pkgMap[distro]?.[pkg] ?? pkg)
  const pkgList = mapped.join(" ")

  switch (distro) {
    case "arch":
      return `sudo pacman -S --needed --noconfirm ${pkgList}`
    case "fedora":
      return `sudo dnf install -y ${pkgList}`
    case "ubuntu":
      return `sudo apt install -y ${pkgList}`
    case "void":
      return `sudo xbps-install -S ${pkgList}`
    case "opensuse":
      return `sudo zypper install -y ${pkgList}`
  }
}

function generateHyprlandConf(c: HyprInstallConfig): string {
  const lines: string[] = []

  lines.push("# Hyprland Configuration")
  lines.push("# Generated by Linux Themer")
  lines.push("")

  // Monitors
  lines.push("# Monitors")
  for (const m of c.monitors) {
    const name = m.name || ","
    lines.push(`monitor = ${name}, ${m.resolution}, ${m.position}, ${m.scale}`)
  }
  lines.push("")

  // Env vars
  if (c.envVars.length > 0) {
    lines.push("# Environment Variables")
    for (const e of c.envVars) {
      lines.push(`env = ${e.key}, ${e.value}`)
    }
    lines.push("")
  }

  // Autostart
  if (c.execOnce.length > 0) {
    lines.push("# Autostart")
    for (const cmd of c.execOnce) {
      lines.push(`exec-once = ${cmd}`)
    }
    lines.push("")
  }

  // Input
  lines.push("input {")
  lines.push(`    kb_layout = ${c.kbLayout}`)
  if (c.kbVariant) lines.push(`    kb_variant = ${c.kbVariant}`)
  if (c.kbOptions) lines.push(`    kb_options = ${c.kbOptions}`)
  lines.push(`    follow_mouse = ${c.followMouse ? 1 : 0}`)
  lines.push(`    sensitivity = ${c.sensitivity}`)
  lines.push(`    repeat_rate = ${c.repeatRate}`)
  lines.push(`    repeat_delay = ${c.repeatDelay}`)
  lines.push(`    natural_scroll = ${c.naturalScroll}`)
  lines.push(`    accel_profile = ${c.mouseAccelProfile}`)
  lines.push("")
  lines.push("    touchpad {")
  lines.push(`        natural_scroll = ${c.touchpadNaturalScroll}`)
  lines.push(`        tap-to-click = ${c.touchpadTapToClick}`)
  lines.push(`        disable_while_typing = ${c.touchpadDisableWhileTyping}`)
  lines.push("    }")
  lines.push("}")
  lines.push("")

  // General
  const gradientBorder = c.borderGradient
    ? `    col.active_border = rgb(${c.activeColor.slice(1)}) rgb(${c.borderGradientColor2.slice(1)}) ${c.borderGradientAngle}deg`
    : `    col.active_border = rgb(${c.activeColor.slice(1)})`

  lines.push("general {")
  lines.push(`    border_size = ${c.borderSize}`)
  lines.push(`    gaps_in = ${c.gapsIn}`)
  lines.push(`    gaps_out = ${c.gapsOut}`)
  lines.push(`    resize_on_border = ${c.resizeOnBorder}`)
  lines.push(`    allow_tearing = ${c.allowTearing}`)
  lines.push(gradientBorder)
  lines.push(`    col.inactive_border = rgb(${c.inactiveColor.slice(1)})`)
  lines.push(`    layout = ${c.layout}`)
  lines.push("}")
  lines.push("")

  // Decoration
  lines.push("decoration {")
  lines.push(`    rounding = ${c.borderRadius}`)
  lines.push(`    active_opacity = ${c.activeOpacity}`)
  lines.push(`    inactive_opacity = ${c.inactiveOpacity}`)
  lines.push(`    dim_inactive = ${c.dimInactive}`)
  lines.push(`    dim_strength = ${c.dimStrength}`)
  lines.push("")
  lines.push("    shadow {")
  lines.push(`        enabled = ${c.shadow}`)
  lines.push(`        range = ${c.shadowRange}`)
  lines.push(`        render_power = ${c.shadowRenderPower}`)
  lines.push(`        color = 0x${c.shadowColor.slice(1)}`)
  lines.push("    }")
  lines.push("")
  lines.push("    blur {")
  lines.push(`        enabled = ${c.blurEnabled}`)
  lines.push(`        size = ${c.blurSize}`)
  lines.push(`        passes = ${c.blurPasses}`)
  lines.push(`        vibrancy = ${c.blurVibrancy}`)
  lines.push("    }")
  lines.push("}")
  lines.push("")

  // Animations
  lines.push("animations {")
  lines.push(`    enabled = ${c.animationEnabled}`)
  if (c.animationEnabled) {
    lines.push("")
    lines.push("    bezier = smooth, 0.05, 0.9, 0.1, 1.05")
    lines.push("    bezier = quick, 0.25, 1, 0.5, 1")
    lines.push("")
    const speed = (7 / c.animationSpeed).toFixed(0)
    const style = c.animationStyle === "default" ? "" : c.animationStyle
    lines.push(`    animation = windows, 1, ${speed}, smooth, ${style}`)
    lines.push(`    animation = windowsOut, 1, ${speed}, smooth, ${c.animationStyle === "popin" ? "popin 80%" : style}`)
    lines.push(`    animation = fade, 1, ${speed}, smooth`)
    lines.push(`    animation = workspaces, 1, ${(6 / c.animationSpeed).toFixed(0)}, smooth, ${c.animationStyle === "slide" ? "slide" : "fade"}`)
  }
  lines.push("}")
  lines.push("")

  // Layout
  if (c.layout === "dwindle") {
    lines.push("dwindle {")
    lines.push("    pseudotile = true")
    lines.push("    preserve_split = true")
    lines.push("}")
  } else {
    lines.push("master {")
    lines.push("    new_status = master")
    lines.push("}")
  }
  lines.push("")

  // Misc
  lines.push("misc {")
  lines.push("    force_default_wallpaper = 0")
  lines.push("    disable_hyprland_logo = true")
  lines.push("}")
  lines.push("")

  // Window Rules
  if (c.windowRules.length > 0) {
    lines.push("# Window Rules")
    for (const rule of c.windowRules) {
      for (const r of rule.rules) {
        lines.push(`windowrulev2 = ${r}, ${rule.match}`)
      }
    }
    lines.push("")
  }

  // Keybinds
  lines.push("# Keybinds")
  for (const bind of c.keybinds) {
    const mods = bind.mods.join(" ")
    const args = bind.args ? `, ${bind.args}` : ""
    lines.push(`bind = ${mods}, ${bind.key}, ${bind.action}${args}`)
  }
  lines.push("")

  // Mouse binds
  lines.push("# Mouse binds")
  lines.push("bindm = SUPER, mouse:272, movewindow")
  lines.push("bindm = SUPER, mouse:273, resizewindow")

  return lines.join("\n")
}

function generateWaybarConfig(c: HyprInstallConfig): string {
  return JSON.stringify(
    {
      layer: "top",
      position: c.barPosition,
      height: c.barHeight,
      spacing: c.barModuleSpacing,
      "modules-left": ["hyprland/workspaces"],
      "modules-center": ["clock"],
      "modules-right": [
        "pulseaudio",
        "network",
        ...(c.packages.includes("brightnessctl") ? ["backlight"] : []),
        "battery",
        "tray",
      ],
      "hyprland/workspaces": {
        "disable-scroll": false,
        "all-outputs": true,
      },
      clock: {
        format: "{:%H:%M}",
        "format-alt": "{:%A, %B %d, %Y}",
        "tooltip-format": "<tt>{calendar}</tt>",
      },
      battery: {
        states: { warning: 30, critical: 15 },
        format: "{icon} {capacity}%",
        "format-icons": ["", "", "", "", ""],
      },
      network: {
        "format-wifi": " {signalStrength}%",
        "format-ethernet": " {ipaddr}",
        "format-disconnected": "⚠ Disconnected",
      },
      pulseaudio: {
        format: "{icon} {volume}%",
        "format-muted": " Muted",
        "format-icons": { default: ["", "", ""] },
        "on-click": "pavucontrol",
      },
    },
    null,
    2
  )
}

function generateWaybarCSS(c: HyprInstallConfig): string {
  return `/* Waybar CSS — Generated by Linux Themer */

* {
    font-family: "JetBrains Mono", "Font Awesome 6 Free", monospace;
    font-size: ${c.barFontSize + 2}px;
}

window#waybar {
    background-color: ${c.barBg};
    color: ${c.barText};
    opacity: ${c.barOpacity};${c.barBorderRadius > 0 ? `\n    border-radius: ${c.barBorderRadius}px;` : ""}${c.barMargin > 0 ? `\n    margin: ${c.barMargin}px;` : ""}
}

#workspaces button {
    padding: 2px 8px;
    color: ${c.barText};
    background: transparent;
    border-radius: ${c.barModuleRadius}px;
    margin: 0 ${c.barModuleSpacing}px;
    border: none;
}

#workspaces button.active {
    background: ${c.accentColor};
    color: ${c.barBg};
}

#workspaces button:hover {
    background: rgba(255, 255, 255, 0.1);
}

#clock,
#network,
#pulseaudio,
#battery,
#backlight,
#tray {
    padding: 2px 10px;
    margin: 4px ${c.barModuleSpacing}px;
    background: ${c.barModuleBg};
    border-radius: ${c.barModuleRadius}px;
    color: ${c.barText};
}

#clock {
    color: ${c.accentColor};
    font-weight: bold;
}

#battery.warning {
    color: #f9e2af;
}

#battery.critical {
    color: #f38ba8;
}`
}

export function generateInstallScript(config: HyprInstallConfig): string {
  const lines: string[] = []

  lines.push("#!/bin/bash")
  lines.push("")
  lines.push("# ╔══════════════════════════════════════════════════════════════╗")
  lines.push("# ║  Hyprland Installer — Generated by Linux Themer             ║")
  lines.push("# ║  https://linux-themer.dev                                   ║")
  lines.push("# ╚══════════════════════════════════════════════════════════════╝")
  lines.push("")
  lines.push('set -e')
  lines.push("")

  // Colors for output
  lines.push("# Colors")
  lines.push('GREEN="\\033[0;32m"')
  lines.push('BLUE="\\033[0;34m"')
  lines.push('YELLOW="\\033[0;33m"')
  lines.push('NC="\\033[0m"')
  lines.push("")

  lines.push('echo -e "${BLUE}╔══════════════════════════════════════════╗${NC}"')
  lines.push('echo -e "${BLUE}║     Hyprland Installer                   ║${NC}"')
  lines.push('echo -e "${BLUE}╚══════════════════════════════════════════╝${NC}"')
  lines.push('echo ""')
  lines.push("")

  // Install packages
  lines.push("# ── Install Packages ──────────────────────────────────────────")
  lines.push('echo -e "${YELLOW}Installing packages...${NC}"')
  lines.push(getInstallCommand(config.distro, config.packages))
  lines.push('echo -e "${GREEN}✓ Packages installed${NC}"')
  lines.push('echo ""')
  lines.push("")

  // Create directories
  lines.push("# ── Create Config Directories ─────────────────────────────────")
  lines.push("mkdir -p ~/.config/hypr")
  lines.push("mkdir -p ~/.config/waybar")
  lines.push("mkdir -p ~/.config/dunst")
  lines.push('echo -e "${GREEN}✓ Config directories created${NC}"')
  lines.push("")

  // Write hyprland.conf
  const hyprConf = generateHyprlandConf(config)
  lines.push("# ── Write Hyprland Config ─────────────────────────────────────")
  lines.push('echo -e "${YELLOW}Writing hyprland.conf...${NC}"')
  lines.push("cat > ~/.config/hypr/hyprland.conf << 'HYPRCONF'")
  lines.push(hyprConf)
  lines.push("HYPRCONF")
  lines.push('echo -e "${GREEN}✓ hyprland.conf written${NC}"')
  lines.push("")

  // Write waybar config
  const waybarConfig = generateWaybarConfig(config)
  lines.push("# ── Write Waybar Config ───────────────────────────────────────")
  lines.push('echo -e "${YELLOW}Writing waybar config...${NC}"')
  lines.push("cat > ~/.config/waybar/config.jsonc << 'WAYBARCONF'")
  lines.push(waybarConfig)
  lines.push("WAYBARCONF")
  lines.push('echo -e "${GREEN}✓ Waybar config written${NC}"')
  lines.push("")

  // Write waybar CSS
  const waybarCSS = generateWaybarCSS(config)
  lines.push("# ── Write Waybar CSS ──────────────────────────────────────────")
  lines.push('echo -e "${YELLOW}Writing waybar style.css...${NC}"')
  lines.push("cat > ~/.config/waybar/style.css << 'WAYBARCSS'")
  lines.push(waybarCSS)
  lines.push("WAYBARCSS")
  lines.push('echo -e "${GREEN}✓ Waybar CSS written${NC}"')
  lines.push("")

  // Write basic dunst config
  if (config.packages.includes("dunst")) {
    lines.push("# ── Write Dunst Config ───────────────────────────────────────")
    lines.push('echo -e "${YELLOW}Writing dunst config...${NC}"')
    lines.push("cat > ~/.config/dunst/dunstrc << 'DUNSTCONF'")
    lines.push("[global]")
    lines.push(`    frame_color = "${config.accentColor}"`)
    lines.push("    font = JetBrains Mono 10")
    lines.push(`    frame_width = ${config.borderSize}`)
    lines.push(`    corner_radius = ${config.borderRadius}`)
    lines.push("")
    lines.push("[urgency_low]")
    lines.push(`    background = "${config.windowBg}"`)
    lines.push(`    foreground = "${config.barText}"`)
    lines.push("")
    lines.push("[urgency_normal]")
    lines.push(`    background = "${config.windowBg}"`)
    lines.push(`    foreground = "${config.barText}"`)
    lines.push("")
    lines.push("[urgency_critical]")
    lines.push(`    background = "${config.windowBg}"`)
    lines.push('    foreground = "#f38ba8"')
    lines.push(`    frame_color = "#f38ba8"`)
    lines.push("DUNSTCONF")
    lines.push('echo -e "${GREEN}✓ Dunst config written${NC}"')
    lines.push("")
  }

  // Done
  lines.push("# ── Done ─────────────────────────────────────────────────────")
  lines.push('echo ""')
  lines.push('echo -e "${GREEN}╔══════════════════════════════════════════╗${NC}"')
  lines.push('echo -e "${GREEN}║     Installation Complete!               ║${NC}"')
  lines.push('echo -e "${GREEN}╚══════════════════════════════════════════╝${NC}"')
  lines.push('echo ""')
  lines.push('echo -e "Your Hyprland setup is ready."')
  lines.push('echo -e "Log out and select ${BLUE}Hyprland${NC} from your display manager."')
  lines.push('echo -e "Or run: ${BLUE}Hyprland${NC} from a TTY."')

  return lines.join("\n")
}
