"use client"

import { useMemo } from "react"
import { useNiriconf } from "./config-context"
import type { NiriconfConfig } from "./config-context"

export function generateNiriKdl(config: NiriconfConfig): string {
  const lines: string[] = []

  lines.push("// Niri Configuration")
  lines.push("// Generated by Linux Themer")
  lines.push("")

  // Environment variables
  if (config.envVars.length > 0) {
    lines.push("// Environment Variables")
    lines.push("environment {")
    for (const e of config.envVars) {
      lines.push(`    ${e.key} "${e.value}"`)
    }
    lines.push("}")
    lines.push("")
  }

  // Input
  lines.push("input {")
  lines.push("    keyboard {")
  lines.push("        xkb {")
  lines.push(`            layout "${config.kbLayout}"`)
  if (config.kbVariant) lines.push(`            variant "${config.kbVariant}"`)
  if (config.kbOptions) lines.push(`            options "${config.kbOptions}"`)
  lines.push("        }")
  lines.push(`        repeat-rate ${config.repeatRate}`)
  lines.push(`        repeat-delay ${config.repeatDelay}`)
  lines.push("    }")
  lines.push("")
  lines.push("    touchpad {")
  if (config.touchpadTapToClick) lines.push("        tap")
  if (config.touchpadNaturalScroll) lines.push("        natural-scroll")
  if (config.touchpadDisableWhileTyping) lines.push("        dwt")
  lines.push(`        accel-profile "${config.mouseAccelProfile}"`)
  lines.push("    }")
  lines.push("")
  lines.push("    mouse {")
  if (config.naturalScroll) lines.push("        natural-scroll")
  lines.push(`        accel-profile "${config.mouseAccelProfile}"`)
  lines.push("    }")
  lines.push("}")
  lines.push("")

  // Layout
  lines.push("layout {")
  lines.push(`    gaps ${config.gapsIn}`)
  lines.push(`    center-focused-column "${config.centerFocusedColumn}"`)
  lines.push("")
  lines.push("    preset-column-widths {")
  lines.push("        proportion 0.33333")
  lines.push("        proportion 0.5")
  lines.push("        proportion 0.66667")
  lines.push("    }")
  lines.push("")
  lines.push(`    default-column-width { ${config.defaultColumnWidth}; }`)
  lines.push("")
  lines.push("    focus-ring {")
  lines.push(`        width ${config.focusRingWidth}`)
  lines.push(`        active-color "${config.focusRingActiveColor}"`)
  lines.push(`        inactive-color "${config.focusRingInactiveColor}"`)
  lines.push("    }")
  lines.push("")
  lines.push("    border {")
  lines.push("        off")
  lines.push("    }")
  lines.push("")
  lines.push("    struts {")
  lines.push(`        left ${config.gapsOut}`)
  lines.push(`        right ${config.gapsOut}`)
  lines.push(`        top ${config.gapsOut}`)
  lines.push(`        bottom ${config.gapsOut}`)
  lines.push("    }")
  lines.push("}")
  lines.push("")

  // Decoration
  lines.push("prefer-no-csd")
  lines.push("")

  // Animations
  const easing = config.animationStyle === "spring"
    ? "spring damping-ratio=0.6 stiffness=800 epsilon=0.0001"
    : config.animationStyle === "ease-out-expo"
    ? 'easing-curve "ease-out-expo"'
    : 'easing-curve "ease-out-cubic"'

  lines.push("animations {")
  if (!config.animationEnabled) {
    lines.push("    off")
  } else {
    lines.push(`    slowdown ${config.animationSpeed}`)
    lines.push("")
    lines.push("    workspace-switch {")
    lines.push(`        ${easing}`)
    lines.push(`        duration-ms ${Math.round(250 / config.animationSpeed)}`)
    lines.push("    }")
    lines.push("")
    lines.push("    window-open {")
    lines.push(`        ${easing}`)
    lines.push(`        duration-ms ${Math.round(200 / config.animationSpeed)}`)
    lines.push("    }")
    lines.push("")
    lines.push("    window-close {")
    lines.push(`        ${easing}`)
    lines.push(`        duration-ms ${Math.round(150 / config.animationSpeed)}`)
    lines.push("    }")
    lines.push("")
    lines.push("    horizontal-view-movement {")
    lines.push(`        ${easing}`)
    lines.push(`        duration-ms ${Math.round(250 / config.animationSpeed)}`)
    lines.push("    }")
    lines.push("")
    lines.push("    window-movement {")
    lines.push(`        ${easing}`)
    lines.push(`        duration-ms ${Math.round(200 / config.animationSpeed)}`)
    lines.push("    }")
    lines.push("")
    lines.push("    window-resize {")
    lines.push(`        ${easing}`)
    lines.push(`        duration-ms ${Math.round(200 / config.animationSpeed)}`)
    lines.push("    }")
  }
  lines.push("}")
  lines.push("")

  // Window Rules
  lines.push("// Window Rules")
  lines.push("window-rule {")
  lines.push(`    geometry-corner-radius ${config.borderRadius}`)
  lines.push("    clip-to-geometry true")
  lines.push("}")
  lines.push("")

  if (config.windowRules.length > 0) {
    for (const rule of config.windowRules) {
      lines.push("window-rule {")
      lines.push(`    match ${rule.match}`)
      for (const r of rule.rules) {
        lines.push(`    ${r}`)
      }
      lines.push("}")
      lines.push("")
    }
  }

  // Spawn at startup
  if (config.spawnAtStartup.length > 0) {
    lines.push("// Autostart")
    for (const cmd of config.spawnAtStartup) {
      const parts = cmd.split(" ")
      if (parts.length > 1) {
        lines.push(`spawn-at-startup "${parts[0]}" ${parts.slice(1).map(a => `"${a}"`).join(" ")}`)
      } else {
        lines.push(`spawn-at-startup "${cmd}"`)
      }
    }
    lines.push("")
  }

  // Keybinds
  lines.push("binds {")
  for (const bind of config.keybinds) {
    const mods = bind.mods.join("+")
    const key = bind.key
    const args = bind.args ? ` "${bind.args}"` : ""
    lines.push(`    ${mods}+${key} { ${bind.action}${args}; }`)
  }
  lines.push("}")

  return lines.join("\n")
}

type TokenType = "comment" | "section" | "key" | "value" | "keyword" | "text" | "string" | "number"

interface Token {
  type: TokenType
  text: string
}

function tokenizeKdlLine(line: string): Token[] {
  const trimmed = line.trimStart()

  if (trimmed.startsWith("//")) {
    return [{ type: "comment", text: line }]
  }

  if (trimmed.endsWith("{")) {
    return [{ type: "section", text: line }]
  }

  if (trimmed === "}") {
    return [{ type: "section", text: line }]
  }

  if (trimmed === "") {
    return [{ type: "text", text: line }]
  }

  // Tokenize with string and number detection
  const tokens: Token[] = []
  const parts = line.split(/("(?:[^"\\]|\\.)*")/g)

  for (const part of parts) {
    if (!part) continue

    if (part.startsWith('"') && part.endsWith('"')) {
      tokens.push({ type: "string", text: part })
    } else {
      // Split by whitespace, keeping whitespace
      const words = part.split(/(\s+)/)
      for (const word of words) {
        if (!word) continue
        if (/^\s+$/.test(word)) {
          tokens.push({ type: "text", text: word })
        } else if (/^-?\d+(\.\d+)?$/.test(word) || /^\d+%$/.test(word)) {
          tokens.push({ type: "number", text: word })
        } else if (word === "true" || word === "false" || word === "off" || word === "on" || word === "tap" || word === "natural-scroll" || word === "dwt" || word === "prefer-no-csd") {
          tokens.push({ type: "keyword", text: word })
        } else if (word.endsWith(";") || word === "{" || word === "}") {
          tokens.push({ type: "section", text: word })
        } else {
          tokens.push({ type: "key", text: word })
        }
      }
    }
  }

  return tokens
}

const TOKEN_COLORS: Record<TokenType, string> = {
  comment: "text-muted-foreground/60",
  section: "text-accent font-medium",
  key: "text-foreground",
  value: "text-muted-foreground",
  keyword: "text-amber-400",
  text: "text-foreground",
  string: "text-green-400",
  number: "text-amber-400",
}

export function NiriConfigPreview() {
  const { config } = useNiriconf()

  const confText = useMemo(() => generateNiriKdl(config), [config])
  const lines = useMemo(() => confText.split("\n"), [confText])

  return (
    <div className="h-full w-full overflow-auto bg-[#0d0d0d] p-6 font-mono text-xs leading-relaxed">
      <div className="min-w-0">
        {lines.map((line, i) => {
          const tokens = tokenizeKdlLine(line)
          return (
            <div key={i} className="flex">
              <span className="inline-block w-8 shrink-0 select-none text-right pr-4 text-muted-foreground/30">
                {i + 1}
              </span>
              <span className="whitespace-pre">
                {tokens.map((token, j) => (
                  <span key={j} className={TOKEN_COLORS[token.type]}>
                    {token.text}
                  </span>
                ))}
              </span>
            </div>
          )
        })}
      </div>
    </div>
  )
}
